/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Student_Registry;

import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author MDTus
 */
public class Update_data extends javax.swing.JFrame {
Connection conn;
ResultSet rs;
PreparedStatement pst;
    /**
     * Creates new form Update_data
     */
    public Update_data() {
        super("Update Student Details");
        initComponents();
        conn = Javaconnetc.ConnecrDb();
        Icon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void Icon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("university.png")));
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        sscsub = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        dep = new javax.swing.JTextField();
        sem = new javax.swing.JTextField();
        sess = new javax.swing.JTextField();
        hscsubmit = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        sex = new javax.swing.JTextField();
        number = new javax.swing.JTextField();
        birth = new javax.swing.JTextField();
        pnumber = new javax.swing.JTextField();
        sec = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        mname = new javax.swing.JTextField();
        curadd = new javax.swing.JTextField();
        peradd = new javax.swing.JTextField();
        ad_date = new javax.swing.JTextField();
        sscgpa = new javax.swing.JTextField();
        hscgpa = new javax.swing.JTextField();
        schoolname = new javax.swing.JTextField();
        collagename = new javax.swing.JTextField();
        sscboard = new javax.swing.JTextField();
        hscboard = new javax.swing.JTextField();
        sscsession = new javax.swing.JTextField();
        hscsession = new javax.swing.JTextField();
        sscyear = new javax.swing.JTextField();
        hscyear = new javax.swing.JTextField();
        Update = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Logout = new javax.swing.JMenuItem();
        Admin = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();
        About = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        view_delete_class = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        View_Delete_Student_Details = new javax.swing.JMenuItem();
        View_Delete_Class_Details = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 51), 3, true), "Update", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 51, 51))); // NOI18N

        jLabel1.setForeground(new java.awt.Color(255, 255, 153));
        jLabel1.setText("ID:");

        ID.setBackground(new java.awt.Color(255, 255, 153));
        ID.setForeground(new java.awt.Color(153, 0, 0));

        Search.setBackground(new java.awt.Color(0, 139, 152));
        Search.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Search.setForeground(new java.awt.Color(102, 0, 102));
        Search.setIcon(new javax.swing.ImageIcon("D:\\Programming\\Java\\University Project\\L-3 T-1\\DBMS Student Registry\\Student Registry\\src\\Student_Registry\\Search.png")); // NOI18N
        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 153));
        jLabel2.setText("Name:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 153));
        jLabel3.setText("ID:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 153));
        jLabel4.setText("Department:");

        jLabel5.setForeground(new java.awt.Color(255, 255, 153));
        jLabel5.setText("Sex:");

        jLabel6.setForeground(new java.awt.Color(255, 255, 153));
        jLabel6.setText("Semister:");

        jLabel7.setForeground(new java.awt.Color(255, 255, 153));
        jLabel7.setText("Session:");

        jLabel8.setForeground(new java.awt.Color(255, 255, 153));
        jLabel8.setText("Mobile Number:");

        jLabel9.setForeground(new java.awt.Color(255, 255, 153));
        jLabel9.setText("Section:");

        jLabel10.setForeground(new java.awt.Color(255, 255, 153));
        jLabel10.setText("Father Name:");

        jLabel11.setForeground(new java.awt.Color(255, 255, 153));
        jLabel11.setText("Mother Name:");

        jLabel12.setForeground(new java.awt.Color(255, 255, 153));
        jLabel12.setText("Admission Date:");

        jLabel13.setForeground(new java.awt.Color(255, 255, 153));
        jLabel13.setText("Date of Birth:");

        jLabel14.setForeground(new java.awt.Color(255, 255, 153));
        jLabel14.setText("Parent Mobile No.:");

        jLabel15.setForeground(new java.awt.Color(255, 255, 153));
        jLabel15.setText("Current Address:");

        jLabel16.setForeground(new java.awt.Color(255, 255, 153));
        jLabel16.setText("Permanent Address:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 153));
        jLabel17.setText("S.S.C Details:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 153));
        jLabel18.setText("H.S.C Details:");

        jLabel19.setForeground(new java.awt.Color(255, 255, 153));
        jLabel19.setText("S.S.C. GPA:");

        jLabel20.setForeground(new java.awt.Color(255, 255, 153));
        jLabel20.setText("S.S.C.  Certificte Submit:");

        jLabel21.setForeground(new java.awt.Color(255, 255, 153));
        jLabel21.setText("School Name:");

        jLabel22.setForeground(new java.awt.Color(255, 255, 153));
        jLabel22.setText("S.S.C Board:");

        jLabel23.setForeground(new java.awt.Color(255, 255, 153));
        jLabel23.setText("S.S.C Session:");

        jLabel24.setForeground(new java.awt.Color(255, 255, 153));
        jLabel24.setText("S.S.C Year");

        jLabel25.setForeground(new java.awt.Color(255, 255, 153));
        jLabel25.setText("H.S.C Year");

        jLabel26.setForeground(new java.awt.Color(255, 255, 153));
        jLabel26.setText("H.S.C Session:");

        jLabel27.setForeground(new java.awt.Color(255, 255, 153));
        jLabel27.setText("H.S.C Board:");

        jLabel28.setForeground(new java.awt.Color(255, 255, 153));
        jLabel28.setText("Collage/School Name:");

        jLabel29.setForeground(new java.awt.Color(255, 255, 153));
        jLabel29.setText("H.S.C.  Certificte Submit:");

        jLabel30.setForeground(new java.awt.Color(255, 255, 153));
        jLabel30.setText("H.S.C. GPA:");

        sscsub.setBackground(new java.awt.Color(255, 255, 153));

        Name.setBackground(new java.awt.Color(255, 255, 153));
        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });

        dep.setBackground(new java.awt.Color(255, 255, 153));

        sem.setBackground(new java.awt.Color(255, 255, 153));

        sess.setBackground(new java.awt.Color(255, 255, 153));

        hscsubmit.setBackground(new java.awt.Color(255, 255, 153));

        id.setBackground(new java.awt.Color(255, 255, 153));

        sex.setBackground(new java.awt.Color(255, 255, 153));

        number.setBackground(new java.awt.Color(255, 255, 153));

        birth.setBackground(new java.awt.Color(255, 255, 153));

        pnumber.setBackground(new java.awt.Color(255, 255, 153));

        sec.setBackground(new java.awt.Color(255, 255, 153));

        fname.setBackground(new java.awt.Color(255, 255, 153));

        mname.setBackground(new java.awt.Color(255, 255, 153));

        curadd.setBackground(new java.awt.Color(255, 255, 153));

        peradd.setBackground(new java.awt.Color(255, 255, 153));

        ad_date.setBackground(new java.awt.Color(255, 255, 153));

        sscgpa.setBackground(new java.awt.Color(255, 255, 153));

        hscgpa.setBackground(new java.awt.Color(255, 255, 153));

        schoolname.setBackground(new java.awt.Color(255, 255, 153));

        collagename.setBackground(new java.awt.Color(255, 255, 153));

        sscboard.setBackground(new java.awt.Color(255, 255, 153));

        hscboard.setBackground(new java.awt.Color(255, 255, 153));

        sscsession.setBackground(new java.awt.Color(255, 255, 153));

        hscsession.setBackground(new java.awt.Color(255, 255, 153));

        sscyear.setBackground(new java.awt.Color(255, 255, 153));

        hscyear.setBackground(new java.awt.Color(255, 255, 153));

        Update.setBackground(new java.awt.Color(0, 139, 152));
        Update.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Update.setForeground(new java.awt.Color(102, 102, 0));
        Update.setIcon(new javax.swing.ImageIcon("D:\\Programming\\Java\\University Project\\L-3 T-1\\DBMS Student Registry\\Student Registry\\src\\Student_Registry\\update.png")); // NOI18N
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 0, 102));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(198, 198, 198)
                                        .addComponent(jLabel7))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(110, 110, 110)
                                        .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Search)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(54, 54, 54))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13)
                                .addGap(66, 66, 66))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(39, 39, 39))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(sess, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel22)
                                            .addComponent(jLabel23)
                                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ad_date)
                                            .addComponent(mname)
                                            .addComponent(fname)
                                            .addComponent(sscsub)
                                            .addComponent(Name)
                                            .addComponent(dep)
                                            .addComponent(sem, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sec)
                                            .addComponent(sscgpa)
                                            .addComponent(schoolname)
                                            .addComponent(sscboard)
                                            .addComponent(sscsession)
                                            .addComponent(sscyear, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hscsubmit)
                            .addComponent(id)
                            .addComponent(sex)
                            .addComponent(number)
                            .addComponent(birth)
                            .addComponent(pnumber)
                            .addComponent(curadd)
                            .addComponent(peradd)
                            .addComponent(hscgpa)
                            .addComponent(collagename)
                            .addComponent(hscboard)
                            .addComponent(hscsession)
                            .addComponent(hscyear, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE))))
                .addGap(57, 57, 57))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(dep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(sem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13)
                    .addComponent(birth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel14)
                    .addComponent(pnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel15)
                    .addComponent(mname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(curadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel16)
                    .addComponent(peradd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ad_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(sscgpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(sscsub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(schoolname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(sscboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(sscsession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(sscyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(hscgpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(hscsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(collagename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(hscboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(hscsession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(hscyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34)
                .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 102, 102));
        jMenuBar1.setForeground(new java.awt.Color(0, 102, 102));

        jMenu1.setBackground(new java.awt.Color(0, 139, 152));
        jMenu1.setForeground(new java.awt.Color(0, 139, 152));
        jMenu1.setIcon(new javax.swing.ImageIcon("D:\\Programming\\Java\\University Project\\L-3 T-1\\DBMS Student Registry\\Student Registry\\src\\Student_Registry\\Manue.png")); // NOI18N
        jMenu1.setText("Manue");

        Logout.setBackground(new java.awt.Color(0, 102, 102));
        Logout.setForeground(new java.awt.Color(255, 255, 153));
        Logout.setIcon(new javax.swing.ImageIcon("D:\\Programming\\Java\\University Project\\L-3 T-1\\DBMS Student Registry\\Student Registry\\src\\Student_Registry\\Logout.png")); // NOI18N
        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        jMenu1.add(Logout);

        Admin.setBackground(new java.awt.Color(0, 102, 102));
        Admin.setForeground(new java.awt.Color(255, 255, 153));
        Admin.setIcon(new javax.swing.ImageIcon("D:\\Programming\\Java\\University Project\\L-3 T-1\\DBMS Student Registry\\Student Registry\\src\\Student_Registry\\admin.png")); // NOI18N
        Admin.setText("Admin");
        Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminActionPerformed(evt);
            }
        });
        jMenu1.add(Admin);

        Exit.setBackground(new java.awt.Color(0, 102, 102));
        Exit.setForeground(new java.awt.Color(255, 255, 153));
        Exit.setIcon(new javax.swing.ImageIcon("D:\\Programming\\Java\\University Project\\L-3 T-1\\DBMS Student Registry\\Student Registry\\src\\Student_Registry\\X.png")); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jMenu1.add(Exit);

        About.setBackground(new java.awt.Color(0, 102, 102));
        About.setForeground(new java.awt.Color(255, 255, 153));
        About.setIcon(new javax.swing.ImageIcon("D:\\Programming\\Java\\University Project\\L-3 T-1\\DBMS Student Registry\\Student Registry\\src\\Student_Registry\\info-about.png")); // NOI18N
        About.setText("About");
        About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutActionPerformed(evt);
            }
        });
        jMenu1.add(About);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(0, 139, 152));
        jMenu2.setForeground(new java.awt.Color(0, 139, 152));
        jMenu2.setIcon(new javax.swing.ImageIcon("D:\\Programming\\Java\\University Project\\L-3 T-1\\DBMS Student Registry\\Student Registry\\src\\Student_Registry\\upload.png")); // NOI18N
        jMenu2.setText("Insert");

        view_delete_class.setBackground(new java.awt.Color(0, 102, 102));
        view_delete_class.setForeground(new java.awt.Color(255, 255, 153));
        view_delete_class.setIcon(new javax.swing.ImageIcon("D:\\Programming\\Java\\University Project\\L-3 T-1\\DBMS Student Registry\\Student Registry\\src\\Student_Registry\\upload.png")); // NOI18N
        view_delete_class.setText("Register Student");
        view_delete_class.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_delete_classActionPerformed(evt);
            }
        });
        jMenu2.add(view_delete_class);

        jMenuBar1.add(jMenu2);

        jMenu3.setBackground(new java.awt.Color(0, 139, 152));
        jMenu3.setForeground(new java.awt.Color(0, 139, 152));
        jMenu3.setIcon(new javax.swing.ImageIcon("D:\\Programming\\Java\\University Project\\L-3 T-1\\DBMS Student Registry\\Student Registry\\src\\Student_Registry\\task.png")); // NOI18N
        jMenu3.setText("View/Delete");

        View_Delete_Student_Details.setBackground(new java.awt.Color(0, 102, 102));
        View_Delete_Student_Details.setForeground(new java.awt.Color(255, 255, 153));
        View_Delete_Student_Details.setIcon(new javax.swing.ImageIcon("D:\\Programming\\Java\\University Project\\L-3 T-1\\DBMS Student Registry\\Student Registry\\src\\Student_Registry\\One Man.png")); // NOI18N
        View_Delete_Student_Details.setText("View/Delete Student Details");
        View_Delete_Student_Details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_Delete_Student_DetailsActionPerformed(evt);
            }
        });
        jMenu3.add(View_Delete_Student_Details);

        View_Delete_Class_Details.setBackground(new java.awt.Color(0, 102, 102));
        View_Delete_Class_Details.setForeground(new java.awt.Color(255, 255, 153));
        View_Delete_Class_Details.setIcon(new javax.swing.ImageIcon("D:\\Programming\\Java\\University Project\\L-3 T-1\\DBMS Student Registry\\Student Registry\\src\\Student_Registry\\Men.png")); // NOI18N
        View_Delete_Class_Details.setText("View all students");
        View_Delete_Class_Details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_Delete_Class_DetailsActionPerformed(evt);
            }
        });
        jMenu3.add(View_Delete_Class_Details);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1088, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1102, 717));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        About ob = new About();
        ob.setVisible(true);
    }//GEN-LAST:event_AboutActionPerformed

    private void View_Delete_Student_DetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_Delete_Student_DetailsActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        View_Student_Details ob = new View_Student_Details();
        ob.setVisible(true);
    }//GEN-LAST:event_View_Delete_Student_DetailsActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Login ob = new Login();
        ob.setVisible(true);
    }//GEN-LAST:event_LogoutActionPerformed

    private void AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Admin_Block ob = new Admin_Block();
        ob.setVisible(true);
    }//GEN-LAST:event_AdminActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void view_delete_classActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_delete_classActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Entry_Data ob = new Entry_Data();
        ob.setVisible(true);
    }//GEN-LAST:event_view_delete_classActionPerformed

    private void View_Delete_Class_DetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_Delete_Class_DetailsActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        View_Class_Details ob = new View_Class_Details();
        ob.setVisible(true);
    }//GEN-LAST:event_View_Delete_Class_DetailsActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
        String sql = "select * from STUDENT_DATABASE where STUDENT_ID = ?";
        try{
            pst = conn.prepareStatement(sql);
            pst.setString(1, ID.getText());
            rs = pst.executeQuery();
            if(rs.next()){
                
                String add1 = rs.getString("STUDENT_NAME");
                Name.setText(add1);
                
                
                String add2 = rs.getString("DEPARTMENR");
                dep.setText(add2);
                
                
                String add3 = rs.getString("SEMISTER");
                sem.setText(add3);
                
                
                String add4 = rs.getString("STUDY_SESSION");
                sess.setText(add4);
                
                
                String add5 = rs.getString("SECTION");
                sec.setText(add5);
                
                
                String add6 = rs.getString("STUDENT_ID");
                id.setText(add6);
                
                
                String add7 = rs.getString("SEX");
                sex.setText(add7);
                
                
                String add8 = rs.getString("STUDENT_NUMBER");
                number.setText(add8);
                
                
                String add9 = rs.getString("DATE_OF_BIRTH");
                birth.setText(add9);
                
                
                String add10 = rs.getString("PARENT_NUMBER");
                pnumber.setText(add10);
                
                
                String add11 = rs.getString("CURRENT_ADDRESS");
                curadd.setText(add11);
                
                
                String add12 = rs.getString("PERMANENT_ADDRESS");
                peradd.setText(add12);
                
                
                String add13 = rs.getString("SSC_CERTIFICATE_SUBMIT");
                sscsub.setText(add13);
                
                
                String add14 = rs.getString("SSC_GPA");
                sscgpa.setText(add14);
                
                
                String add15 = rs.getString("SCHOOL_NAME");
                schoolname.setText(add15);
                
                
                String add16 = rs.getString("SSC_BORD");
                sscboard.setText(add16);
                
                
                String add17 = rs.getString("SSC_SESSION");
                sscsession.setText(add17);
                
                
                String add18 = rs.getString("SSC_YEAR");
                sscyear.setText(add18);
                
                
                String add19 = rs.getString("HSC_GPA");
                hscgpa.setText(add19);
                
                
                String add20 = rs.getString("HSC_CIRTIFICATE_SUBMIT");
                hscsubmit.setText(add20);
                
                
                String add21 = rs.getString("COLLAGE_NAME");
                collagename.setText(add21);
                
                
                String add22 = rs.getString("HSC_BORD");
                hscboard.setText(add22);
                
                
                String add23 = rs.getString("HSC_SESSION");
                hscsession.setText(add23);
                
                
                String add24 = rs.getString("HSC_YEAR");
                hscyear.setText(add24);
                
                
                String add25 = rs.getString("FATHER_NAME");
                fname.setText(add25);
                
                
                String add26 = rs.getString("MOTHER_NAME");
                mname.setText(add26);
                
                
                String add27 = rs.getString("ADMISSION_DATE");
                ad_date.setText(add27);
                                
                rs.close();
                pst.close();
            }
            else{
                JOptionPane.showMessageDialog(null, "Student is Not Found");
            }
        }catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
        }finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_SearchActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
       
        try{
            String sql = "update STUDENT_DATABASE set STUDENT_NAME=?,FATHER_NAME=?,MOTHER_NAME=?,STUDENT_NUMBER=?,PARENT_NUMBER=?,"
                    + "SSC_GPA=?,SSC_CERTIFICATE_SUBMIT=?,SCHOOL_NAME=?,SSC_BORD=?,SSC_SESSION=?,SSC_YEAR=?,HSC_GPA=?,HSC_CIRTIFICATE_SUBMIT=?,"
                    + "COLLAGE_NAME=?,HSC_BORD=?,HSC_SESSION=?,HSC_YEAR=?,PERMANENT_ADDRESS=?,CURRENT_ADDRESS=?,DEPARTMENR=?,"
                    + "STUDENT_ID=?,SECTION=?,STUDY_SESSION=?,SEMISTER=?,ADMISSION_DATE=?,DATE_OF_BIRTH=?,SEX=? where STUDENT_ID=?";
            
            pst=conn.prepareStatement(sql);
            pst.setString(1, Name.getText());
            pst.setString(2, fname.getText());
            pst.setString(3, mname.getText());
            pst.setString(4, number.getText());
            pst.setString(5, pnumber.getText());
            pst.setString(6, sscgpa.getText());
            pst.setString(7, sscsub.getText());
            pst.setString(8, schoolname.getText());
            pst.setString(9, sscboard.getText());
            pst.setString(10, sscsession.getText());
            pst.setString(11, sscyear.getText());
            pst.setString(12, hscgpa.getText());
            pst.setString(13, hscsubmit.getText());
            pst.setString(14, collagename.getText());
            pst.setString(15, hscboard.getText());
            pst.setString(16, hscsession.getText());
            pst.setString(17, hscyear.getText());
            pst.setString(18, peradd.getText());
            pst.setString(19, curadd.getText());
            pst.setString(20, dep.getText());
            pst.setString(21, id.getText());
            pst.setString(22, sec.getText());
            pst.setString(23, sess.getText());
            pst.setString(24, sem.getText());
            pst.setString(25, ad_date.getText());
            pst.setString(26, birth.getText());
            pst.setString(27, sex.getText());
            pst.setString(28, ID.getText());
            
            rs = pst.executeQuery();
            
            if(rs.next()){
                rs.close();
                pst.close();
                
                JOptionPane.showMessageDialog(null, "Updated");
                setVisible(false);
                View_Student_Details ob = new View_Student_Details();
                ob.setVisible(true);
            }
        }catch(HeadlessException | SQLException e){
           JOptionPane.showMessageDialog(null, e);
       }        
    }//GEN-LAST:event_UpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update_data().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem About;
    private javax.swing.JMenuItem Admin;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JTextField ID;
    private javax.swing.JMenuItem Logout;
    private javax.swing.JTextField Name;
    private javax.swing.JButton Search;
    private javax.swing.JButton Update;
    private javax.swing.JMenuItem View_Delete_Class_Details;
    private javax.swing.JMenuItem View_Delete_Student_Details;
    private javax.swing.JTextField ad_date;
    private javax.swing.JTextField birth;
    private javax.swing.JTextField collagename;
    private javax.swing.JTextField curadd;
    private javax.swing.JTextField dep;
    private javax.swing.JTextField fname;
    private javax.swing.JTextField hscboard;
    private javax.swing.JTextField hscgpa;
    private javax.swing.JTextField hscsession;
    private javax.swing.JTextField hscsubmit;
    private javax.swing.JTextField hscyear;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField mname;
    private javax.swing.JTextField number;
    private javax.swing.JTextField peradd;
    private javax.swing.JTextField pnumber;
    private javax.swing.JTextField schoolname;
    private javax.swing.JTextField sec;
    private javax.swing.JTextField sem;
    private javax.swing.JTextField sess;
    private javax.swing.JTextField sex;
    private javax.swing.JTextField sscboard;
    private javax.swing.JTextField sscgpa;
    private javax.swing.JTextField sscsession;
    private javax.swing.JTextField sscsub;
    private javax.swing.JTextField sscyear;
    private javax.swing.JMenuItem view_delete_class;
    // End of variables declaration//GEN-END:variables
}
