/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Student_Registry;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author MDTus
 */
public class View_Student_Details extends javax.swing.JFrame {
Connection conn;
ResultSet rs;
PreparedStatement pst;
    /**
     * Creates new form View_Student_Details
     */
    public View_Student_Details() {
        super("View Student Details");
        initComponents();
        conn = Javaconnetc.ConnecrDb();
        Icon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void Icon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("university.png")));
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        dep = new javax.swing.JLabel();
        sem = new javax.swing.JLabel();
        sess = new javax.swing.JLabel();
        sec = new javax.swing.JLabel();
        fname = new javax.swing.JLabel();
        mname = new javax.swing.JLabel();
        ad_date = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        sex = new javax.swing.JLabel();
        number = new javax.swing.JLabel();
        birth = new javax.swing.JLabel();
        pnumber = new javax.swing.JLabel();
        curadd = new javax.swing.JLabel();
        peradd = new javax.swing.JLabel();
        hscgpa = new javax.swing.JLabel();
        hscsubmit = new javax.swing.JLabel();
        collagename = new javax.swing.JLabel();
        hscboard = new javax.swing.JLabel();
        hscsession = new javax.swing.JLabel();
        hscyear = new javax.swing.JLabel();
        sscgpa = new javax.swing.JLabel();
        sscsub = new javax.swing.JLabel();
        schoolname = new javax.swing.JLabel();
        sscboard = new javax.swing.JLabel();
        sscsession = new javax.swing.JLabel();
        sscyear = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        updatedata = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Logout = new javax.swing.JMenuItem();
        Admin = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        about = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Register_student = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        view_delete_class = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        update = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 51), 3, true), "View/Delete", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 51, 51))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Student ID");

        Search.setBackground(new java.awt.Color(0, 139, 152));
        Search.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Search.setForeground(new java.awt.Color(102, 0, 51));
        Search.setIcon(new javax.swing.ImageIcon("D:\\Programming\\Java\\University Project\\L-3 T-1\\DBMS Student Registry\\Student Registry\\src\\Student_Registry\\Search.png")); // NOI18N
        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(53, 53, 53))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(mname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ad_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sscgpa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sscsub, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(schoolname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sscboard, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sscsession, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sscyear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(sem, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(sec, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(sess, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(dep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                        .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                        .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(hscgpa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(collagename, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hscboard, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hscsession, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hscyear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                        .addComponent(hscsubmit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(peradd, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                        .addComponent(curadd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(birth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(number, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(205, 205, 205)
                                .addComponent(jLabel8)
                                .addGap(85, 85, 85))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(Name))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(dep))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel28)
                                    .addComponent(sem)
                                    .addComponent(sess))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(sec))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(fname))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(mname))
                                .addGap(58, 58, 58)
                                .addComponent(jLabel29)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sscgpa))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(sscsub))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(schoolname))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(sscboard))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(sscsession))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(sscyear)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(hscgpa)
                                .addGap(18, 18, 18)
                                .addComponent(hscsubmit)
                                .addGap(18, 18, 18)
                                .addComponent(collagename)
                                .addGap(18, 18, 18)
                                .addComponent(hscboard)
                                .addGap(18, 18, 18)
                                .addComponent(hscsession)
                                .addGap(18, 18, 18)
                                .addComponent(hscyear))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(id))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(sex))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(number))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel24)
                                    .addComponent(birth))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel23)
                                    .addComponent(pnumber))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel25)
                                    .addComponent(curadd))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel26)
                                    .addComponent(ad_date)
                                    .addComponent(jLabel22)
                                    .addComponent(peradd))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel30)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel32)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel33)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel34)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel35)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel36)))))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        Back.setBackground(new java.awt.Color(0, 139, 152));
        Back.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Back.setForeground(new java.awt.Color(0, 51, 0));
        Back.setIcon(new javax.swing.ImageIcon("D:\\Programming\\Java\\University Project\\L-3 T-1\\DBMS Student Registry\\Student Registry\\src\\Student_Registry\\Back.png")); // NOI18N
        Back.setText("Start Page");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        updatedata.setBackground(new java.awt.Color(0, 139, 152));
        updatedata.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        updatedata.setForeground(new java.awt.Color(0, 51, 51));
        updatedata.setIcon(new javax.swing.ImageIcon("D:\\Programming\\Java\\University Project\\L-3 T-1\\DBMS Student Registry\\Student Registry\\src\\Student_Registry\\update.png")); // NOI18N
        updatedata.setText("Update");
        updatedata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatedataActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 139, 152));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon("D:\\Programming\\Java\\University Project\\L-3 T-1\\DBMS Student Registry\\Student Registry\\src\\Student_Registry\\delete.png")); // NOI18N
        jButton1.setText("Delete\n");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Back)
                            .addGap(18, 18, 18)
                            .addComponent(jButton1)
                            .addGap(32, 32, 32)
                            .addComponent(updatedata))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Search)
                            .addGap(651, 651, 651)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Back)
                            .addComponent(jButton1))
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                        .addComponent(updatedata)
                        .addGap(56, 56, 56))))
        );

        jMenu1.setBackground(new java.awt.Color(0, 139, 152));
        jMenu1.setForeground(new java.awt.Color(0, 139, 152));
        jMenu1.setIcon(new javax.swing.ImageIcon("D:\\Programming\\Java\\University Project\\L-3 T-1\\DBMS Student Registry\\Student Registry\\src\\Student_Registry\\Manue.png")); // NOI18N
        jMenu1.setText("Manue");

        Logout.setBackground(new java.awt.Color(0, 139, 152));
        Logout.setForeground(new java.awt.Color(255, 255, 153));
        Logout.setIcon(new javax.swing.ImageIcon("D:\\Programming\\Java\\University Project\\L-3 T-1\\DBMS Student Registry\\Student Registry\\src\\Student_Registry\\Logout.png")); // NOI18N
        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        jMenu1.add(Logout);

        Admin.setBackground(new java.awt.Color(0, 139, 152));
        Admin.setForeground(new java.awt.Color(255, 255, 153));
        Admin.setIcon(new javax.swing.ImageIcon("D:\\Programming\\Java\\University Project\\L-3 T-1\\DBMS Student Registry\\Student Registry\\src\\Student_Registry\\admin.png")); // NOI18N
        Admin.setText("Admin");
        Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminActionPerformed(evt);
            }
        });
        jMenu1.add(Admin);

        exit.setBackground(new java.awt.Color(0, 139, 152));
        exit.setForeground(new java.awt.Color(255, 255, 153));
        exit.setIcon(new javax.swing.ImageIcon("D:\\Programming\\Java\\University Project\\L-3 T-1\\DBMS Student Registry\\Student Registry\\src\\Student_Registry\\X.png")); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenu1.add(exit);

        about.setBackground(new java.awt.Color(0, 139, 152));
        about.setForeground(new java.awt.Color(255, 255, 153));
        about.setIcon(new javax.swing.ImageIcon("D:\\Programming\\Java\\University Project\\L-3 T-1\\DBMS Student Registry\\Student Registry\\src\\Student_Registry\\info-about.png")); // NOI18N
        about.setText("About");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        jMenu1.add(about);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(0, 139, 152));
        jMenu2.setForeground(new java.awt.Color(0, 139, 152));
        jMenu2.setIcon(new javax.swing.ImageIcon("D:\\Programming\\Java\\University Project\\L-3 T-1\\DBMS Student Registry\\Student Registry\\src\\Student_Registry\\upload.png")); // NOI18N
        jMenu2.setText("Insert");

        Register_student.setBackground(new java.awt.Color(0, 139, 152));
        Register_student.setForeground(new java.awt.Color(255, 255, 153));
        Register_student.setIcon(new javax.swing.ImageIcon("D:\\Programming\\Java\\University Project\\L-3 T-1\\DBMS Student Registry\\Student Registry\\src\\Student_Registry\\upload.png")); // NOI18N
        Register_student.setText("Register Student");
        Register_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Register_studentActionPerformed(evt);
            }
        });
        jMenu2.add(Register_student);

        jMenuBar1.add(jMenu2);

        jMenu3.setBackground(new java.awt.Color(0, 139, 152));
        jMenu3.setForeground(new java.awt.Color(0, 139, 152));
        jMenu3.setIcon(new javax.swing.ImageIcon("D:\\Programming\\Java\\University Project\\L-3 T-1\\DBMS Student Registry\\Student Registry\\src\\Student_Registry\\task.png")); // NOI18N
        jMenu3.setText("View/Delete");

        view_delete_class.setBackground(new java.awt.Color(0, 139, 152));
        view_delete_class.setForeground(new java.awt.Color(255, 255, 153));
        view_delete_class.setIcon(new javax.swing.ImageIcon("D:\\Programming\\Java\\University Project\\L-3 T-1\\DBMS Student Registry\\Student Registry\\src\\Student_Registry\\Men.png")); // NOI18N
        view_delete_class.setText("View all students");
        view_delete_class.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_delete_classActionPerformed(evt);
            }
        });
        jMenu3.add(view_delete_class);

        jMenuBar1.add(jMenu3);

        jMenu4.setBackground(new java.awt.Color(0, 139, 152));
        jMenu4.setForeground(new java.awt.Color(0, 139, 152));
        jMenu4.setIcon(new javax.swing.ImageIcon("D:\\Programming\\Java\\University Project\\L-3 T-1\\DBMS Student Registry\\Student Registry\\src\\Student_Registry\\update.png")); // NOI18N
        jMenu4.setText("Update");

        update.setBackground(new java.awt.Color(0, 139, 152));
        update.setForeground(new java.awt.Color(255, 255, 153));
        update.setIcon(new javax.swing.ImageIcon("D:\\Programming\\Java\\University Project\\L-3 T-1\\DBMS Student Registry\\Student Registry\\src\\Student_Registry\\update.png")); // NOI18N
        update.setText("Update Student Data");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jMenu4.add(update);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1169, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 742, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1183, 804));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Register_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Register_studentActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Entry_Data ob = new Entry_Data();
        ob.setVisible(true);
    }//GEN-LAST:event_Register_studentActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Login ob = new Login();
        ob.setVisible(true);
    }//GEN-LAST:event_LogoutActionPerformed

    private void AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Admin_Block ob = new Admin_Block();
        ob.setVisible(true);
    }//GEN-LAST:event_AdminActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        About ob = new About();
        ob.setVisible(true);
    }//GEN-LAST:event_aboutActionPerformed

    private void view_delete_classActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_delete_classActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        View_Class_Details ob = new View_Class_Details();
        ob.setVisible(true);
    }//GEN-LAST:event_view_delete_classActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Update_data ob = new Update_data();
        ob.setVisible(true);
    }//GEN-LAST:event_updateActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Entry_Data ob = new Entry_Data();
        ob.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void updatedataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatedataActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Update_data ob = new Update_data();
        ob.setVisible(true);
    }//GEN-LAST:event_updatedataActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
        String sql = "select * from STUDENT_DATABASE where STUDENT_ID = ?";
        try{
            pst = conn.prepareStatement(sql);
            pst.setString(1, ID.getText());
            rs = pst.executeQuery();
            if(rs.next()){
                jLabel2.setText("Name:");
                String add1 = rs.getString("STUDENT_NAME");
                Name.setText(add1);
                
                jLabel3.setText("Department:");
                String add2 = rs.getString("DEPARTMENR");
                dep.setText(add2);
                
                jLabel4.setText("Semister:");
                String add3 = rs.getString("SEMISTER");
                sem.setText(add3);
                
                jLabel28.setText("Session:");
                String add4 = rs.getString("STUDY_SESSION");
                sess.setText(add4);
                
                jLabel5.setText("Section:");
                String add5 = rs.getString("SECTION");
                sec.setText(add5);
                
                jLabel19.setText("ID:");
                String add6 = rs.getString("STUDENT_ID");
                id.setText(add6);
                
                jLabel20.setText("Sex:");
                String add7 = rs.getString("SEX");
                sex.setText(add7);
                
                jLabel21.setText("Mobile Number:");
                String add8 = rs.getString("STUDENT_NUMBER");
                number.setText(add8);
                
                jLabel24.setText("Date of Birth:");
                String add9 = rs.getString("DATE_OF_BIRTH");
                birth.setText(add9);
                
                jLabel23.setText("Parent Mobile No.:");
                String add10 = rs.getString("PARENT_NUMBER");
                pnumber.setText(add10);
                
                jLabel25.setText("Current Address:");
                String add11 = rs.getString("CURRENT_ADDRESS");
                curadd.setText(add11);
                
                jLabel26.setText("Permanent Address:");
                String add12 = rs.getString("PERMANENT_ADDRESS");
                peradd.setText(add12);
                
                jLabel27.setText("S.S.C. Certificate Submit:");
                String add13 = rs.getString("SSC_CERTIFICATE_SUBMIT");
                sscsub.setText(add13);
                
                jLabel9.setText("S.S.C. GPA:");
                String add14 = rs.getString("SSC_GPA");
                sscgpa.setText(add14);
                
                jLabel10.setText("School Name:");
                String add15 = rs.getString("SCHOOL_NAME");
                schoolname.setText(add15);
                
                jLabel11.setText("S.S.C. Board:");
                String add16 = rs.getString("SSC_BORD");
                sscboard.setText(add16);
                
                jLabel12.setText("S.S.C Session:");
                String add17 = rs.getString("SSC_SESSION");
                sscsession.setText(add17);
                
                jLabel13.setText("S.S.C Year:");
                String add18 = rs.getString("SSC_YEAR");
                sscyear.setText(add18);
                
                jLabel31.setText("H.S.C GPA:");
                String add19 = rs.getString("HSC_GPA");
                hscgpa.setText(add19);
                
                jLabel32.setText("H.S.C Cirtificate Submit:");
                String add20 = rs.getString("HSC_CIRTIFICATE_SUBMIT");
                hscsubmit.setText(add20);
                
                jLabel33.setText("Collage/School Name:");
                String add21 = rs.getString("COLLAGE_NAME");
                collagename.setText(add21);
                
                jLabel34.setText("H.S.C Board:");
                String add22 = rs.getString("HSC_BORD");
                hscboard.setText(add22);
                
                jLabel35.setText("H.S.C Session:");
                String add23 = rs.getString("HSC_SESSION");
                hscsession.setText(add23);
                
                jLabel36.setText("H.S.C Year:");
                String add24 = rs.getString("HSC_YEAR");
                hscyear.setText(add24);
                
                jLabel6.setText("Father Name:");
                String add25 = rs.getString("FATHER_NAME");
                fname.setText(add25);
                
                jLabel7.setText("Mother Name:");
                String add26 = rs.getString("MOTHER_NAME");
                mname.setText(add26);
                
                jLabel22.setText("Admission Date:");
                String add27 = rs.getString("ADMISSION_DATE");
                ad_date.setText(add27);
                
                jLabel29.setText("S.S.C. Details:");
                jLabel30.setText("H.S.C. Details:");
                
                rs.close();
                pst.close();
            }
            else{
                JOptionPane.showMessageDialog(null, "Student is Not Found");
            }
        }catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
        }finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_SearchActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sql = "delete from STUDENT_DATABASE where Student_Id=?";
        try{
            pst = conn.prepareStatement(sql);
            pst.setString(1,ID.getText());
            JOptionPane.showMessageDialog(null, "Sdudent Data Deleted");
            pst.execute();
            setVisible(false);
            Entry_Data ob = new Entry_Data();
            ob.setVisible(true);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Student_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Student_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Student_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Student_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Student_Details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Admin;
    private javax.swing.JButton Back;
    private javax.swing.JTextField ID;
    private javax.swing.JMenuItem Logout;
    private javax.swing.JLabel Name;
    private javax.swing.JMenuItem Register_student;
    private javax.swing.JButton Search;
    private javax.swing.JMenuItem about;
    private javax.swing.JLabel ad_date;
    private javax.swing.JLabel birth;
    private javax.swing.JLabel collagename;
    private javax.swing.JLabel curadd;
    private javax.swing.JLabel dep;
    private javax.swing.JMenuItem exit;
    private javax.swing.JLabel fname;
    private javax.swing.JLabel hscboard;
    private javax.swing.JLabel hscgpa;
    private javax.swing.JLabel hscsession;
    private javax.swing.JLabel hscsubmit;
    private javax.swing.JLabel hscyear;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel mname;
    private javax.swing.JLabel number;
    private javax.swing.JLabel peradd;
    private javax.swing.JLabel pnumber;
    private javax.swing.JLabel schoolname;
    private javax.swing.JLabel sec;
    private javax.swing.JLabel sem;
    private javax.swing.JLabel sess;
    private javax.swing.JLabel sex;
    private javax.swing.JLabel sscboard;
    private javax.swing.JLabel sscgpa;
    private javax.swing.JLabel sscsession;
    private javax.swing.JLabel sscsub;
    private javax.swing.JLabel sscyear;
    private javax.swing.JMenuItem update;
    private javax.swing.JButton updatedata;
    private javax.swing.JMenuItem view_delete_class;
    // End of variables declaration//GEN-END:variables
}
