/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Student_Registry;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author MDTus
 */
public class View_Class_Details extends javax.swing.JFrame {
Connection conn;
ResultSet rs;
PreparedStatement pst;
    /**
     * Creates new form View_Class_Details
     */
    public View_Class_Details() {
        super("Class Information");
        initComponents();
        conn = Javaconnetc.ConnecrDb();
        jTable1();
        Icon();
    }
    
    
    public void jTable1(){
//        try{
//            String sql = "select * from STUDENT_DATABASE";
//            pst = conn.prepareStatement(sql);
//            rs = pst.executeQuery();
//            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
//        }catch(Exception e){
//            JOptionPane.showMessageDialog(null, e);
//        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void Icon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("university.png")));
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dep = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        sem = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        sec = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        sess = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Login = new javax.swing.JMenuItem();
        Admin = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();
        About = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Register_Student = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        View_delete_student_details = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        update_Student_data = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 51), 3, true), "View Class Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 51, 51))); // NOI18N

        jTable1.setBackground(new java.awt.Color(255, 255, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.setBackground(new java.awt.Color(102, 15, 92));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 153));
        jLabel1.setText("Department");

        dep.setBackground(new java.awt.Color(255, 255, 153));
        dep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CSE", "EEE", "CIVIL", "ME", "Physics", "Chemestry", "Math", "DBA", "Low", "English", " " }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 153));
        jLabel2.setText("Section");

        sem.setBackground(new java.awt.Color(255, 255, 153));
        sem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Spring", "Summer", "Fall" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 153));
        jLabel3.setText("Semister");

        sec.setBackground(new java.awt.Color(255, 255, 153));
        sec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 153));
        jLabel4.setText("Session");

        sess.setBackground(new java.awt.Color(255, 255, 153));

        Search.setBackground(new java.awt.Color(0, 139, 152));
        Search.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Search.setForeground(new java.awt.Color(51, 0, 51));
        Search.setIcon(new javax.swing.ImageIcon("D:\\Programming\\Java\\University Project\\L-3 T-1\\DBMS Student Registry\\Student Registry\\src\\Student_Registry\\Search.png")); // NOI18N
        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1443, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(dep, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(sem, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(sec, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(sess, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(Search)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(sec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(sess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(Search))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 102, 102));
        jMenuBar1.setForeground(new java.awt.Color(0, 102, 102));

        jMenu1.setBackground(new java.awt.Color(0, 139, 152));
        jMenu1.setForeground(new java.awt.Color(0, 102, 102));
        jMenu1.setIcon(new javax.swing.ImageIcon("D:\\Programming\\Java\\University Project\\L-3 T-1\\DBMS Student Registry\\Student Registry\\src\\Student_Registry\\Manue.png")); // NOI18N
        jMenu1.setText("Manue");

        Login.setBackground(new java.awt.Color(0, 102, 102));
        Login.setForeground(new java.awt.Color(255, 255, 153));
        Login.setIcon(new javax.swing.ImageIcon("D:\\Programming\\Java\\University Project\\L-3 T-1\\DBMS Student Registry\\Student Registry\\src\\Student_Registry\\Logout.png")); // NOI18N
        Login.setText("Logout");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        jMenu1.add(Login);

        Admin.setBackground(new java.awt.Color(0, 102, 102));
        Admin.setForeground(new java.awt.Color(255, 255, 153));
        Admin.setIcon(new javax.swing.ImageIcon("D:\\Programming\\Java\\University Project\\L-3 T-1\\DBMS Student Registry\\Student Registry\\src\\Student_Registry\\admin.png")); // NOI18N
        Admin.setText("Admin");
        Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminActionPerformed(evt);
            }
        });
        jMenu1.add(Admin);

        Exit.setBackground(new java.awt.Color(0, 102, 102));
        Exit.setForeground(new java.awt.Color(255, 255, 153));
        Exit.setIcon(new javax.swing.ImageIcon("D:\\Programming\\Java\\University Project\\L-3 T-1\\DBMS Student Registry\\Student Registry\\src\\Student_Registry\\X.png")); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jMenu1.add(Exit);

        About.setBackground(new java.awt.Color(0, 102, 102));
        About.setForeground(new java.awt.Color(255, 255, 153));
        About.setIcon(new javax.swing.ImageIcon("D:\\Programming\\Java\\University Project\\L-3 T-1\\DBMS Student Registry\\Student Registry\\src\\Student_Registry\\info-about.png")); // NOI18N
        About.setText("About");
        About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutActionPerformed(evt);
            }
        });
        jMenu1.add(About);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(0, 139, 152));
        jMenu2.setForeground(new java.awt.Color(0, 102, 102));
        jMenu2.setIcon(new javax.swing.ImageIcon("D:\\Programming\\Java\\University Project\\L-3 T-1\\DBMS Student Registry\\Student Registry\\src\\Student_Registry\\upload.png")); // NOI18N
        jMenu2.setText("Insert");

        Register_Student.setBackground(new java.awt.Color(0, 102, 102));
        Register_Student.setForeground(new java.awt.Color(255, 255, 153));
        Register_Student.setIcon(new javax.swing.ImageIcon("D:\\Programming\\Java\\University Project\\L-3 T-1\\DBMS Student Registry\\Student Registry\\src\\Student_Registry\\upload.png")); // NOI18N
        Register_Student.setText("Register Student");
        Register_Student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Register_StudentActionPerformed(evt);
            }
        });
        jMenu2.add(Register_Student);

        jMenuBar1.add(jMenu2);

        jMenu3.setBackground(new java.awt.Color(0, 139, 152));
        jMenu3.setForeground(new java.awt.Color(0, 102, 102));
        jMenu3.setIcon(new javax.swing.ImageIcon("D:\\Programming\\Java\\University Project\\L-3 T-1\\DBMS Student Registry\\Student Registry\\src\\Student_Registry\\task.png")); // NOI18N
        jMenu3.setText("View/Delete");

        View_delete_student_details.setBackground(new java.awt.Color(0, 102, 102));
        View_delete_student_details.setForeground(new java.awt.Color(255, 255, 153));
        View_delete_student_details.setIcon(new javax.swing.ImageIcon("D:\\Programming\\Java\\University Project\\L-3 T-1\\DBMS Student Registry\\Student Registry\\src\\Student_Registry\\One Man.png")); // NOI18N
        View_delete_student_details.setText("View/Delete Student Details");
        View_delete_student_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_delete_student_detailsActionPerformed(evt);
            }
        });
        jMenu3.add(View_delete_student_details);

        jMenuBar1.add(jMenu3);

        jMenu4.setBackground(new java.awt.Color(0, 139, 152));
        jMenu4.setForeground(new java.awt.Color(0, 139, 152));
        jMenu4.setIcon(new javax.swing.ImageIcon("D:\\Programming\\Java\\University Project\\L-3 T-1\\DBMS Student Registry\\Student Registry\\src\\Student_Registry\\update.png")); // NOI18N
        jMenu4.setText("Update");

        update_Student_data.setBackground(new java.awt.Color(0, 102, 102));
        update_Student_data.setForeground(new java.awt.Color(255, 255, 153));
        update_Student_data.setIcon(new javax.swing.ImageIcon("D:\\Programming\\Java\\University Project\\L-3 T-1\\DBMS Student Registry\\Student Registry\\src\\Student_Registry\\update.png")); // NOI18N
        update_Student_data.setText("Update Student Data");
        update_Student_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_Student_dataActionPerformed(evt);
            }
        });
        jMenu4.add(update_Student_data);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1477, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1491, 710));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
         setVisible(false);
        Login ob = new Login();
        ob.setVisible(true);
    }//GEN-LAST:event_LoginActionPerformed

    private void AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Admin_Block ob = new Admin_Block();
        ob.setVisible(true);
    }//GEN-LAST:event_AdminActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        About ob = new About();
        ob.setVisible(true);
    }//GEN-LAST:event_AboutActionPerformed

    private void Register_StudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Register_StudentActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Entry_Data ob = new Entry_Data();
        ob.setVisible(true);
    }//GEN-LAST:event_Register_StudentActionPerformed

    private void View_delete_student_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_delete_student_detailsActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        View_Student_Details ob = new View_Student_Details();
        ob.setVisible(true);
    }//GEN-LAST:event_View_delete_student_detailsActionPerformed

    private void update_Student_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_Student_dataActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Update_data ob = new Update_data();
        ob.setVisible(true);
    }//GEN-LAST:event_update_Student_dataActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "select STUDENT_ID as ID,STUDENT_NAME as Name,STUDENT_NUMBER as Mobile,DATE_OF_BIRTH,SEX,FATHER_NAME,"
                    + "MOTHER_NAME,PARENT_NUMBER,PERMANENT_ADDRESS,CURRENT_ADDRESS,ADMISSION_DATE"
                    + "  from STUDENT_DATABASE where DEPARTMENR=? and SEMISTER=? and SECTION=? and STUDY_SESSION=?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, (String) dep.getSelectedItem());
            pst.setString(2, (String) sem.getSelectedItem());
            pst.setString(3, (String) sec.getSelectedItem());
            pst.setString(4, sess.getText());
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Not Found");
        }
    }//GEN-LAST:event_SearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Class_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Class_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Class_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Class_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Class_Details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem About;
    private javax.swing.JMenuItem Admin;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenuItem Login;
    private javax.swing.JMenuItem Register_Student;
    private javax.swing.JButton Search;
    private javax.swing.JMenuItem View_delete_student_details;
    private javax.swing.JComboBox<String> dep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> sec;
    private javax.swing.JComboBox<String> sem;
    private javax.swing.JTextField sess;
    private javax.swing.JMenuItem update_Student_data;
    // End of variables declaration//GEN-END:variables
}
